apiVersion: v1
kind: Pod
metadata:
  name: pod-to-limit-cpu
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
    # resources:
    #   limits:
    #      cpu: 200m
