apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: busybox
    image: busybox:latest
    command:
      - sleep
      - "3600"
    ports:
    - containerPort: 80
  restartPolicy: OnFailure
  serviceAccountName: my-sa
  
