apiVersion: v1
kind: Pod
metadata:
  name: local-pv-pod
spec:
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: local-pv-claim
  containers:
    - name: busybox-a
      image: radial/busyboxplus:curl
      command:
      - sleep
      - "3600"
      volumeMounts:
      - name: local-volume
        mountPath: /pv-data
